### ISSUE TITLE
Panel Questions

### ISSUE THREAD

**Issue by crondog** [vinaysimhabn/msm#1]
Hi,

So I have been playing around with your kernel and the kernel from John Stultz. I have been able to get the kernel booting and accessible from uart. I can get the panel to show the following text "aaannndddrrroooiiiddd___" with some flickering. Is this the furthest that you have got or is the display clear for you?

I just have a couple of questions about your implementation inside panel-jdi-lt070me05000.c
- You give a url to the "data sheet" however I cannot find the pdf of the panel on that link. Is it only the information provided on that page? Are you just getting your information from the android 3.4 source code?
- The initialisation order of the panel is slightly different to the android 3.4 kernel. Is there a reason for this?
- It is my understanding that the JDI panel on the nexus 7 flo is a command panel, so why are you initialising it as a video panel. Is it actually a dual mode panel?

Is there anything that I can do to help out?

**Comment by vinaysimhabn** [comment]
On Tue, Dec 15, 2015 at 7:29 AM, crondog notifications@github.com wrote:

> Hi,
> 
> So I have been playing around with your kernel and the kernel from John
> Stultz I have been able to get the kernel booting and accessible from uart
> I can get the panel to show the following text "aaannndddrrroooiiiddd___"
> with some flickering Is this the furthest that you have got or is the
> display clear for you?es.
> 
>  yes, WIP
> 
> I just have a couple of questions about your implementation inside
> panel-jdi-lt070me05000c
> 
>    -
> 
>    You give a url to the "data sheet" however I cannot find the pdf of
>    the panel on that link Is it only the information provided on that page?
>    Are you just getting your information from the android 34 source code?
> 
> there is not datasheet available. referred few jdi panels for video
> configuration dsi-panel-jdi-dualmipi1-video.dtsi
> 
>    -
> 
>    The initialisation order of the panel is slightly different to the
>    android 34 kernel Is there a reason for this?
> 
> Yes. in 3.4 kernel they had configuring the panel in cmd mode. in 4.3
> right now it is configured as video mode
> 
>    -
> 
>    It is my understanding that the JDI panel on the nexus 7 flo is a
>    command panel, so why are you initialising it as a video panel Is it
>    actually a dual mode panel?
> 
> i guess any command mode panel could be configured as video mode. right
> now in 4.3 there is not CMD mode panel support, only video mode supported.
> WIP
> 
> Is there anything that I can do to help out?
> 
> CMD mode panel is not yet implemented, backlight (pwm, pm8921) ,audio codec
> driver is also not available in 4.3 kernel
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vinaysimhabn/msm/issues/1.

## 

Regards,

Vinay Simha.B.N.

**Comment by crondog** [comment]
Ok thanks for the info

**Comment by vinaysimhabn** [comment]
HI crondog,

display is up in the nexus7

kernel
https://git.linaro.org/people/john.stultz/flo.git/shortlog/refs/heads/flo-WIP

https://wiki.linaro.org/LMG/Kernel/FormFactorEnablement

**Comment by crondog** [comment]
Nice work. I'll play with this when I have some time
